import Head from "next/head";
import Image from "next/image";
// import styles from "../styles/home_profile.css";
import Link from "next/link";

export default function Home() {
  return (
    <div className={"home__profile"}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/*  Top Header Starts Here */}
      <div className="menu__header">
        <header>
          <div className="header__container">
            <div className="header__row__1">
              <div className="row__1__logo">
                <h1>Logo</h1>
              </div>
              <div className="row__1__options">Other Options</div>
            </div>
            <div className="header__row__2">
              <div className="menu__navbar">
                <ul>
                  <li>Home</li>
                  <li>About</li>
                  <li>Contact</li>
                </ul>
              </div>
              <div>Media Section</div>
            </div>
          </div>
        </header>
      </div>
      {/* Top Header Ends Here */}

      {/* Title Bar Starts Here */}
      <div className="titlebar__container">
        <div className="titlebar__text">
          <p>
            A place to Learn, teach and discuss about code. Contribute and get
            rewarded. Serving coding community is our number 1 priority
          </p>
        </div>
      </div>

      {/* Title Bar Ends Here */}
      <div className="container blog__list__container">
        <div className="blog__newsletter">
          <input name="newsletter" type="email" />
        </div>
        <div className="blog__posts__wrapper">
    <div className="blog__post__card">

    </div>
        </div>
      </div>
      <footer className={""}></footer>
    </div>
  );
}
